<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- project info -->
  <groupId>com.ethananddee-cs151-fall2025-game</groupId>
  <artifactId>gameproject</artifactId>
  <version>1.0</version>

  <properties>
    <maven.compiler.source>24</maven.compiler.source>   <!-- For Ethan, match Java version -->
    <maven.compiler.target>24</maven.compiler.target>
    <javafx.version>25</javafx.version>                 <!-- For Ethan, match your JavaFx version -->
  </properties>

  <!-- JavaFX dependencies -->
  <dependencies>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-controls</artifactId>
      <version>${javafx.version}</version>
    </dependency>

    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-fxml</artifactId>
      <version>${javafx.version}</version>
    </dependency>
  </dependencies>

  <!-- Build settings -->
  <build>
    <plugins>
      <!-- JavaFX Maven plugin -->
      <plugin>
        <groupId>org.openjfx</groupId>
        <artifactId>javafx-maven-plugin</artifactId>
        <version>${javafx.version}</version>
        <configuration>
          <!-- For Ethan, we will keep this but test run our games telling Maven which main class to run -->
          <mainClass>game.manager.GameManagerApp</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
